// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://otelzbaiqeqlktawuuyv.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im90ZWx6YmFpcWVxbGt0YXd1dXl2Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDMzODMzNzAsImV4cCI6MjA1ODk1OTM3MH0.LYP50GjlDI6-4OqDIQ5n-bMntOv4_UZAqCfYUdXd_7o";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);